### ISSUE TITLE
E713: Cannot use empty key for Dictionary

### ISSUE THREAD

**Issue by yujiangang** [jszakmeister/markdown2ctags#11]
I find the following error message when I use this plugin:

```
Error detected while processing function tagbar#ToggleWindow..<SNR>148_ToggleWindow..<SNR>148_OpenWindow..<SNR>148_AutoUpdate..<SNR>148_ProcessFile..<SNR>148_ParseTag
line..<SNR>148_ProcessTag..<SNR>148_add_tag_recursive..<SNR>148_add_tag_recursive..<SNR>155_addChild:
line    6:
E713: Cannot use empty key for Dictionary
```

After working on my markdown file for a while, I find the error is caused by || in the section title.
```
# Logical operators ( || ) 
```

This might be a bug.

**Comment by jszakmeister** [comment]
What version of TagBar are you using?  What version of markdown2ctags are you using?  On my install, I don't see an error, though the heading isn't nice because the `|` symbol generally means that it's nested inside something else.  I tried adding a backslash to escape the `|`, but that didn't seem to help.

**Comment by yujiangang** [comment]
I use tagbar of version 2.7 from https://github.com/majutsushi/tagbar. And the markdown2ctags is version 0.2.2.

**Comment by jszakmeister** [comment]
@yujiangang try out the tip of master.  The issue is that `|` is being used as the sro, and it turns out TagBar splits the tagname on it (I was under the impression is was only proper to split the last section of the tagline on it).  At any rate, you'll need to adjust your vim configuration (see the README) so that you use a different character for the scope resolution (`sro`).  This means adjusting the call to markdown2ctags and informing TagBar of the new string being used.  Testing here showed that this works, and if it works for you, I'll cut a new release (0.2.3).

**Comment by yujiangang** [comment]
@jszakmeister It works perfectly. Thank you!
