### ISSUE TITLE
六 替换成 e5

### ISSUE THREAD

**Issue by mvmx3** [jszakmeister/markdown2ctags#16]
我在使用插件的时候  数字 六  被替换成  e5, 这是什么原因?
如果把-sro=» 替换成 '|',那么 会出现没有权限执行的错误

**Comment by jszakmeister** [comment]
Unfortunately, I don't speak your language and cannot understand what the issue is.  Do you know English?  One the surface (and trying to use Google Translate to understand), it looks like it *might* be an encoding-related issue.  But it's really hard to tell from your limited description and zero knowledge of your settings, environment, or what you were trying to use this with.

**Comment by mvmx3** [comment]
https://i.loli.net/2020/01/07/zqXoUM1nBASNe56.png

Like this, all "六" are altered into "\<e5\>"

**Comment by jszakmeister** [comment]
Can you put a copy of the file in a Gist on Github?  It looks like an
encoding issue and the test data would be useful.  What encoding is the
file in UTF-8?  Something else?

Thanks!

**Comment by jszakmeister** [comment]
Any chance you can try out the version on my [better-enc-handling](https://github.com/jszakmeister/markdown2ctags/tree/better-enc-handling) branch?  I'm pretty sure the problem here is that I'm using latin1 encoding underneath the hood and that's breaking some of the processing.  The version in the branch *should* work better.  Let me know what you think! :-)

**Comment by mvmx3** [comment]
I'm sorry I haven't replied to you for so long. I've been too busy in the last ten days. The version is utf-8,which is common version in this area.

**Comment by jszakmeister** [comment]
@1235452356 No worries.  Is it possible for you to try the branch mentioned above?

**Comment by mvmx3** [comment]
Use latin1 is no effect. I gave up,and I decided to replace it with mzlogin/vim-markdown-toc

**Comment by jszakmeister** [comment]
That was not the suggestion... that was me telling you what I did under the
hood and might be causing the issue.  Can you try my better-enc-handling
branch?  I expect that it will resolve the issue.

-John

**Comment by mvmx3** [comment]
I'm sorry that I don't understand the sense of under words before. my english is very bad. better-enc-handling solve my problem.

**Comment by mvmx3** [comment]
There will still be some confusion when using this method.  for example : è®¾ç½® ,æ­£å,

**Comment by mvmx3** [comment]
set fileencodings=utf-8,gb2312,gbk,gb18030
set encoding=utf-8
set langmenu=zh_CN.UTF-8
language message zh_CN.UTF-8
set termencoding=utf-8        
set langmenu=zh_CN.utf-8
This is my  vimrc

**Comment by mvmx3** [comment]
设置   è®¾ç½®

**Comment by jszakmeister** [comment]
> I'm sorry that I don't understand the sense of under words before. my english is very bad. better-enc-handling solve my problem.

I understand--and thank you for trying to bridge the language gap.  I'm glad better-enc-handling helped... I'll look to merge that into master this weekend.

> There will still be some confusion when using this method. for example : è®¾ç½® ,æ­£å,

Can you provide sample text (not an image) that demonstrates the problem?  If so, I can see if I can fix it.  FWIW, I did try with both of your examples to throw it in a document and see the issue, and neither one of your examples showed a problem:

<img width="823" alt="my-vim" src="https://user-images.githubusercontent.com/448087/72662539-76e87b80-39b6-11ea-8231-8a03359cdf0f.png">

If I could reproduce the problem, that would help tremendously.  So a sample document that fails for you would be good a start.

Given other user experiences, I suspect it's possible that something is happening in TagBar or some other vim setting too.

**Comment by mvmx3** [comment]
```
# Javascript 

## 0. 四个例子

## 1. 变量数据类型

## 2. 语句


## 3. 正则

## 4. 异常

## 5. 表单

## 6. 包

## 7. affaf
```

**Comment by mvmx3** [comment]
![深度截图_选择区域_20200118204620](https://user-images.githubusercontent.com/52132505/72663994-9e315e00-3a33-11ea-86f4-80014fd8f538.png)

**Comment by mvmx3** [comment]
before "# 1" , if having a space ,Chinese transforms Garbled

**Comment by jszakmeister** [comment]
Can you pull the latest change in better-enc-handling and try again?

At issue here is trying to know what the file is encoded as.  There are several steps happening here.  One is to read the front of the file and search for a BOM (which is not generally present).  Next I attempt to detect the character set.  In this case, if you have chardet installed, it attempted to detect the encoding which came back with only an 87% confidence.  Next it attempted to just treat the block as UTF-8 and it failed to decode because a code point was incomplete, so it treated the text as latin1.  I changed the strategy a bit... see how it works for you now (it works for me).

And thank you for the data, that helped immensely!

**Comment by mvmx3** [comment]
It solves my problem. Meanwhile , can it compatible neovim ?

**Comment by jszakmeister** [comment]
I released v0.3.0 with these fixes in it and uploaded it to PyPI, and they're fixed on master too.  Thanks for helping to track down the issue.

> It solves my problem. Meanwhile , can it compatible neovim ?

I'm not sure what you mean.  Why is it not compatible with neovim?  I don't see any reason why it shouldn't be.

**Comment by mvmx3** [comment]
Maybe it's because my neovim which is 0.4.3 version is too new. In archlinux,it was downloaded with so high version.
To be honest,I don't know why.

**Comment by jszakmeister** [comment]
I'm not sure what the issue could be.   The way this works is that TagBar executes markdown2ctags to get the ctags data.  As far as I know, Neovim shouldn't be causing a problem at all.  Do you see an error?  How is it not working?  Can you show an example?

**Comment by 1235452356** [comment]
Except Markdown, tagbar works.

![深度截图_dde-desktop_20200123122647](https://user-images.githubusercontent.com/52132505/72956779-fd002a00-3ddb-11ea-963b-7d7f2284eba0.png)


![深度截图_dde-desktop_20200123122728](https://user-images.githubusercontent.com/52132505/72956785-038ea180-3ddc-11ea-834e-8eaddcea1dce.png)

**Comment by mvmx3** [comment]
Except  markdown ,it works

![深度截图_dde-desktop_20200123122647](https://user-images.githubusercontent.com/52132505/72956935-ab0bd400-3ddc-11ea-9e46-8f0dedb8bd17.png)


![深度截图_dde-desktop_20200123122728](https://user-images.githubusercontent.com/52132505/72956940-ae9f5b00-3ddc-11ea-9424-dace7db25925.png)

![深度截图_dde-desktop_20200123123507](https://user-images.githubusercontent.com/52132505/72956973-d098dd80-3ddc-11ea-828a-c2f3e232be5b.png)
