### ISSUE TITLE
wrong tags section layout 

### ISSUE THREAD

**Issue by waruqi** [jszakmeister/markdown2ctags#7]
wrong tags layout for s1, s2, s3

![snip20170228_1](https://cloud.githubusercontent.com/assets/151335/23397153/3904d43a-fdd2-11e6-8433-6db4b62ac20a.png)

**Comment by jszakmeister** [comment]
Thanks for reporting this.  It would have been helpful to have your document in a text format rather than an image so it would be easier for me to reproduce locally.  This is definitely an issue though.  It does beg a few questions about how things should be nested in the sense that if you have this:

```text
## t1
###### ss1
#### s2
```

How should that be rendered in the tree?  The best I can do is say `ss1` and `s2` are at the same level because the only parent to `ss1` is `t1`, unless I create some kind of placeholder.  In your specific case, I can do better.  I'll have to take a look at it when I get some time.

**Comment by jszakmeister** [comment]
Actually, this turned out to be easier than I thought.  Try the current master.

**Comment by waruqi** [comment]
It works perfectly.

Thanks!

**Comment by jszakmeister** [comment]
Great!  Thanks for testing it!
